const USER_LOADING = 'USER_LOADING'
const USER_LOADING_SUCCESS = 'USER_LOADING_SUCCESS'
const USER_LOADING_FAIL = 'USER_LOADING_FAIL'
export {
  USER_LOADING,USER_LOADING_SUCCESS,USER_LOADING_FAIL
};
