const USER_LOGOUT = 'USER_LOGOUT'
const USER_LOADING_SUCCESS = 'USER_LOADING_SUCCESS'
const USER_LOADING_FAIL = 'USER_LOADING_FAIL'

const GET_MOVIES_PHIMLE_FETCHING='GET_MOVIES_PHIMLE_FETCHING';
const GET_MOVIES_PHIMLE_SUCCESS='GET_MOVIES_PHIMLE_SUCCESS';
const GET_MOVIES_PHIMLE_FAIL='GET_MOVIES_PHIMLE_FAIL';

const GET_MOVIES_PHIMBO_FETCHING='GET_MOVIES_PHIMBO_FETCHING';
const GET_MOVIES_PHIMBO_SUCCESS='GET_MOVIES_PHIMBO_SUCCESS';
const GET_MOVIES_PHIMBO_FAIL='GET_MOVIES_PHIMBO_FAIL';

const GET_MOVIES_TVSHOW_FETCHING='GET_MOVIES_TVSHOW_FETCHING';
const GET_MOVIES_TVSHOW_SUCCESS='GET_MOVIES_TVSHOW_SUCCESS';
const GET_MOVIES_TVSHOW_FAIL='GET_MOVIES_TVSHOW_FAIL';

const GET_MOVIES_PHIMLE_FETCHING_MAIN='GET_MOVIES_PHIMLE_FETCHING_MAIN';
const GET_MOVIES_PHIMLE_SUCCESS_MAIN='GET_MOVIES_PHIMLE_SUCCESS_MAIN';
const GET_MOVIES_PHIMLE_FAIL_MAIN='GET_MOVIES_PHIMLE_FAIL_MAIN';

const GET_MOVIES_PHIMBO_FETCHING_MAIN='GET_MOVIES_PHIMBO_FETCHING_MAIN';
const GET_MOVIES_PHIMBO_SUCCESS_MAIN='GET_MOVIES_PHIMBO_SUCCESS_MAIN';
const GET_MOVIES_PHIMBO_FAIL_MAIN='GET_MOVIES_PHIMBO_FAIL_MAIN';

const GET_MOVIES_TVSHOW_FETCHING_MAIN='GET_MOVIES_TVSHOW_FETCHING_MAIN';
const GET_MOVIES_TVSHOW_SUCCESS_MAIN='GET_MOVIES_TVSHOW_SUCCESS_MAIN';
const GET_MOVIES_TVSHOW_FAIL_MAIN='GET_MOVIES_TVSHOW_FAIL_MAIN';

const GET_DETAIL_MOVIE_FETCHING = 'GET_DETAIL_MOVIE_FETCHING';
const GET_DETAIL_MOVIE_SUCCESS = 'GET_DETAIL_MOVIE_SUCCESS';
const GET_DETAIL_MOVIE_FAIL = 'GET_DETAIL_MOVIE_FAIL';

const GET_TOP_MOVIE_FETCHING = 'GET_TOP_MOVIE_FETCHING';
const GET_TOP_MOVIE_SUCCESS = 'GET_TOP_MOVIE_SUCCESS';
const GET_TOP_MOVIE_FAIL = 'GET_TOP_MOVIE_FAIL';
export {
  USER_LOGOUT,
  USER_LOADING_SUCCESS,
  USER_LOADING_FAIL,
  GET_MOVIES_PHIMLE_FETCHING,
  GET_MOVIES_PHIMLE_SUCCESS,
  GET_MOVIES_PHIMLE_FAIL,
  GET_MOVIES_PHIMBO_FETCHING,
  GET_MOVIES_PHIMBO_SUCCESS,
  GET_MOVIES_PHIMBO_FAIL,
  GET_MOVIES_TVSHOW_FETCHING,
  GET_MOVIES_TVSHOW_SUCCESS,
  GET_MOVIES_TVSHOW_FAIL,
  GET_MOVIES_PHIMLE_FETCHING_MAIN,
  GET_MOVIES_PHIMLE_SUCCESS_MAIN,
  GET_MOVIES_PHIMLE_FAIL_MAIN,
  GET_MOVIES_PHIMBO_FETCHING_MAIN,
  GET_MOVIES_PHIMBO_SUCCESS_MAIN,
  GET_MOVIES_PHIMBO_FAIL_MAIN,
  GET_MOVIES_TVSHOW_FETCHING_MAIN,
  GET_MOVIES_TVSHOW_SUCCESS_MAIN,
  GET_MOVIES_TVSHOW_FAIL_MAIN,
  GET_DETAIL_MOVIE_FETCHING,
  GET_DETAIL_MOVIE_SUCCESS,
  GET_DETAIL_MOVIE_FAIL,
  GET_TOP_MOVIE_FETCHING,
  GET_TOP_MOVIE_SUCCESS,
  GET_TOP_MOVIE_FAIL
};
