export default dataNotification =[{
    id:'1',
    title:'Title',
    description:'Description',
    time:'8:30',
    image:'https://raw.githubusercontent.com/react-native-training/react-native-elements-app/master/assets/images/bg_screen1.jpg'
},
{
    id:'2',
    title:'Title',
    description:'Description',
    time:'8:30',
    image:'https://raw.githubusercontent.com/react-native-training/react-native-elements-app/master/assets/images/bg_screen1.jpg'
},
{
    id:'3',
    title:'Title',
    description:'Description',
    time:'8:30',
    image:'https://raw.githubusercontent.com/react-native-training/react-native-elements-app/master/assets/images/bg_screen1.jpg'
}]